version: "3"

services:
  node:
    build: .
    ports:
      - "${PORT:-3333}:3333"
    volumes:
      - ".:/usr/app"
    depends_on:
      - db

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: gostack_gobarber
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
    ports:
      - "5432:5432"
