version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - '${PORT:-3333}:3333'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/usr/app'
    depends_on:
      - db

  db:
    image: 'postgres:alpine'
    container_name: db
    environment:
      POSTGRES_DB: gostack_gobarber
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
    ports:
      - '5432:5432'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
